-- models/PreflopEquity.lua
--
-- Read side of data/preflop_equity.lua (generated by
-- sim/gen_preflop_equity.lua). Two jobs:
--
--   * look up the heads-up preflop equity of one canonical starting-hand
--     class against another, and each class's equity against a random
--     hand (the "how playable is this" ordering), and
--   * sample a MATCHUP whose equity lands in a requested band — the
--     inverse query the showdown construction actually needs. Card
--     realism is decided outcome-first: the hand already knows the player
--     lost a stack, and asks for two hands that make losing a stack look
--     like poker.
--
-- ─── Why rejection sampling ─────────────────────────────────────────────
-- The obvious implementation pre-bins all 28,561 ordered class pairs by
-- equity so a band lookup is O(1). That costs the better part of a
-- megabyte of live tables to save a handful of microseconds on an event
-- that happens a few times a second at most.
--
-- Instead: draw both classes from the same 169-entry weighted
-- distribution the bands want anyway (playable hands, by combo count and
-- equity-vs-random), and keep the draw only if its matchup equity lands
-- in the band. That is exactly the same distribution a pre-binned table
-- would give — conditioning by rejection rather than by bucket — for one
-- small cumulative array per weighting exponent. Bands are wide enough
-- (12.5-25 equity points) that a hit takes a few attempts.

local HandClass = require("models.HandClass")

local PreflopEquity = {}

local DATA = nil          -- the loaded data table
local ROWS = nil          -- DATA.rows
local EQVR = nil          -- DATA.eq_vs_random
local N    = HandClass.COUNT

local byte = string.byte

-- Attempts before a band is declared unservable. Generous: even a narrow
-- band against a hostile weighting hits well inside this, and the caller
-- treats nil as "fall back", not as an error.
local MAX_ATTEMPTS = 400

-- Load the generated table. Accepts an injected data table (the sim
-- passes candidates); defaults to the shipped file.
function PreflopEquity.load(data)
    DATA = data or require("data.preflop_equity")
    ROWS = DATA.rows
    EQVR = DATA.eq_vs_random
    assert(#ROWS == N,
        "preflop_equity: " .. #ROWS .. " rows, expected " .. N)
    assert(#EQVR == N,
        "preflop_equity: " .. #EQVR .. " eq_vs_random entries, expected " .. N)
    PreflopEquity._cum = {}     -- drop cached weightings; data changed
    return PreflopEquity
end

local function ensureLoaded()
    if not ROWS then PreflopEquity.load() end
end

-- Class i's equity against class j, 0..1. Decoded from the packed row
-- with byte arithmetic — no substring allocation on the hot path.
function PreflopEquity.equity(i, j)
    ensureLoaded()
    local p = j * 3 - 2
    local b1, b2, b3 = byte(ROWS[i], p, p + 2)
    return ((b1 - 48) * 100 + (b2 - 48) * 10 + (b3 - 48)) / 1000
end

-- Class i's equity against a uniformly random hand, 0..1. This is the
-- playability ordering: AA ≈ 0.85 at the top, 32o ≈ 0.32 at the bottom.
function PreflopEquity.eqVsRandom(i)
    ensureLoaded()
    return EQVR[i] / 1000
end

-- The best equity-vs-random any class has (AA). Callers that pick hands
-- by weighted rejection need it as the ceiling to compare against.
local _max_eqvr = nil
function PreflopEquity.maxEqVsRandom()
    if _max_eqvr then return _max_eqvr end
    ensureLoaded()
    local best = 0
    for i = 1, N do
        if EQVR[i] > best then best = EQVR[i] end
    end
    _max_eqvr = best / 1000
    return _max_eqvr
end

-- ─── Weighted class distribution ───────────────────────────────────────
-- weight(i) = combos(i) · eqVsRandom(i)^exp
--
-- The combo count keeps the relative frequency of real hands honest (12
-- ways to be dealt AKo, 4 to be dealt AKs, 6 to be dealt AA); the
-- exponent is how much the hand looks like a range rather than a random
-- deal. exp = 0 is a uniform random deal; exp = 4 is showdown-tight.

PreflopEquity._cum = {}

-- `min_eqvr`, when given, zeroes every class below that equity-vs-random,
-- so a draw never has to be thrown away for being too weak a hand. The
-- resulting distribution is identical to filtering by rejection, minus
-- the rejections — and the bands that ask for a strong opponent are
-- exactly the ones where rejection was throwing away most draws.
local function cumulativeFor(exp, min_eqvr)
    local key = exp .. "|" .. (min_eqvr or 0)
    local cached = PreflopEquity._cum[key]
    if cached then return cached end
    ensureLoaded()
    local cum, total, first = {}, 0, nil
    local floor_permille = (min_eqvr or 0) * 1000
    for i = 1, N do
        local w = 0
        if EQVR[i] >= floor_permille then
            w = HandClass.comboCount(i)
            if exp ~= 0 then
                w = w * (EQVR[i] / 1000) ^ exp
            end
            if not first then first = i end
        end
        total = total + w
        cum[i] = total
    end
    cum.total = total
    cum.first  = first
    PreflopEquity._cum[key] = cum
    return cum
end
PreflopEquity._cumulativeFor = cumulativeFor

-- Binary search for the first index whose cumulative weight reaches r.
-- Zero-weight classes leave the array flat, and a flat run can only be
-- entered from below, so they are never selected — except at r = 0
-- exactly, which `first` covers.
local function pickFrom(cum)
    local r = love.math.random() * cum.total
    if r <= 0 then return cum.first or 1 end
    local lo, hi = 1, N
    while lo < hi do
        local mid = math.floor((lo + hi) / 2)
        if cum[mid] < r then lo = mid + 1 else hi = mid end
    end
    return lo
end

-- Draw a single class from the weighted distribution (no band).
function PreflopEquity.sampleClass(exp)
    return pickFrom(cumulativeFor(exp or 0, nil))
end

-- Sample (player_class, opp_class) whose player-side equity is in
-- [lo, hi). `opts.exp` sets the range tightness (default 4);
-- `opts.opp_min_eqvr` additionally requires the opponent to hold a hand
-- worth playing back with (the cooler shapes). Returns nil when the band
-- could not be served — the caller falls back rather than looping.
function PreflopEquity.sampleMatchup(lo, hi, opts)
    opts = opts or {}
    local exp     = opts.exp or 4
    local cum_p   = cumulativeFor(exp, nil)
    local cum_o   = cumulativeFor(exp, opts.opp_min_eqvr)
    if cum_o.total <= 0 then return nil end
    for _ = 1, MAX_ATTEMPTS do
        local i = pickFrom(cum_p)
        local j = pickFrom(cum_o)
        local e = PreflopEquity.equity(i, j)
        if e >= lo and e < hi then return i, j end
    end
    return nil
end

return PreflopEquity
